{% set name = "orjson" %}
{% set version = "2.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 7d0962fde0ab6b0e81cc2a9e6b6665ce14510837a40d0adf5ea0eac7c5d36809
  - url: https://static.rust-lang.org/dist/2020-04-26/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    sha256: a723247878b5b65ec511c86108b9adb99bd1fa9b78ed87986283b93bf9e50d20
    folder: rust-nightly

build:
  number: 0
  skip: true  # [osx or win or py<35]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - posix    # [win]
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
