schema_version: 1

context:
  version: 3.10.18

package:
  name: orjson
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/orjson/orjson-${{ version }}.tar.gz
  sha256: e8da3947d92123eda795b68228cafe2724815621fe35e8e320a9e9593a4bcd53

build:
  number: 1
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: crossenv
    - if: build_platform != target_platform
      then: maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - toml
    - maturin >=1,<2
  run:
    - python

tests:
  - python:
      imports:
        - orjson
  - requirements:
      run:
        - pip
        - mypy
    script:
      - pip check
      - mypy -m orjson

about:
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  homepage: https://github.com/ijl/orjson
  repository: https://github.com/ijl/orjson
  documentation: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - janjagusch
    - EntPyle
    - nehaljwani
    - synapticarbors
