schema_version: 1

context:
  version: "3.11.6"

package:
  name: orjson
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/orjson/orjson-${{ version }}.tar.gz
  sha256: 0a54c72259f35299fd033042367df781c2f66d10252955ca1efb7db309b954cb

build:
  number: 0
  skip: is_freethreading
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - toml
    - maturin >=1,<2
  run:
    - python

tests:
  - python:
      imports:
        - orjson
  - requirements:
      run:
        - pip
        - mypy
    script:
      - pip check
      - mypy -m orjson

about:
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  homepage: https://github.com/ijl/orjson
  repository: https://github.com/ijl/orjson
  documentation: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - janjagusch
    - EntPyle
    - nehaljwani
    - synapticarbors
