schema_version: 1

context:
  version: "3.11.4"

package:
  name: orjson
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/orjson/orjson-${{ version }}.tar.gz
  sha256: 39485f4ab4c9b30a3943cfe99e1a213c4776fb69e8abd68f66b83d5a0b0fdc6d

build:
  number: 0
  script:
    # fix for upstream maturin issue
    - if: build_platform != target_platform and unix and python is startingwith('3.14')
      then:
        - rm -f $PREFIX/lib/python3.14/build-details.json
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - toml
    - maturin >=1,<2
  run:
    - python

tests:
  - python:
      imports:
        - orjson
  - requirements:
      run:
        - pip
        - mypy
    script:
      - pip check
      - mypy -m orjson

about:
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  homepage: https://github.com/ijl/orjson
  repository: https://github.com/ijl/orjson
  documentation: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - janjagusch
    - EntPyle
    - nehaljwani
    - synapticarbors
